# .github/workflows/ci.yml
name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # ---- Backend (root) ----
      - name: Install backend deps
        run: npm ci

      - name: Lint backend
        run: npm run lint --if-present

      - name: Test backend (unit only)
        run: npm test --if-present

      # ---- Frontend (/frontend) ----
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build
